# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(927, 606)
        self.verticalLayoutWidget = QtWidgets.QWidget(GroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 330, 341, 114))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.accountsInquiryBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.accountsInquiryBtn.setObjectName("accountsInquiryBtn")
        self.verticalLayout.addWidget(self.accountsInquiryBtn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fiatKRW = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fiatKRW.setEnabled(True)
        self.fiatKRW.setObjectName("fiatKRW")
        self.horizontalLayout.addWidget(self.fiatKRW)
        self.fiatBTC = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fiatBTC.setObjectName("fiatBTC")
        self.horizontalLayout.addWidget(self.fiatBTC)
        self.fiatUSDT = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fiatUSDT.setObjectName("fiatUSDT")
        self.horizontalLayout.addWidget(self.fiatUSDT)
        self.singleOrderItems = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.singleOrderItems.setEditable(True)
        self.singleOrderItems.setCurrentText("")
        self.singleOrderItems.setObjectName("singleOrderItems")
        self.horizontalLayout.addWidget(self.singleOrderItems)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.singleOrdersInquiry = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.singleOrdersInquiry.setObjectName("singleOrdersInquiry")
        self.verticalLayout.addWidget(self.singleOrdersInquiry)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.undoView = QtWidgets.QUndoView(GroupBox)
        self.undoView.setGeometry(QtCore.QRect(600, 30, 256, 192))
        self.undoView.setObjectName("undoView")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(GroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 561, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        GroupBox.setTitle(_translate("GroupBox", "조회"))
        self.accountsInquiryBtn.setText(_translate("GroupBox", "전체계좌조회"))
        self.fiatKRW.setToolTip(_translate("GroupBox", "KRW마켓을 보여줍니다"))
        self.fiatKRW.setText(_translate("GroupBox", "KRW"))
        self.fiatBTC.setToolTip(_translate("GroupBox", "BTC 마켓을 보여줍니다"))
        self.fiatBTC.setText(_translate("GroupBox", "BTC"))
        self.fiatUSDT.setToolTip(_translate("GroupBox", "USDT 마켓을 보여줍니다"))
        self.fiatUSDT.setText(_translate("GroupBox", "USDT"))
        self.singleOrderItems.setToolTip(_translate("GroupBox", "KRW만지원합니다"))
        self.singleOrdersInquiry.setText(_translate("GroupBox", "단일주문조회"))
        self.pushButton.setText(_translate("GroupBox", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupBox = QtWidgets.QGroupBox()
    ui = Ui_GroupBox()
    ui.setupUi(GroupBox)
    GroupBox.show()
    sys.exit(app.exec_())
